name: quick_blue_linux
description: Linux implementation of the quick_blue plugin.
version: 0.5.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  quick_blue_platform_interface:
    git:
      url: https://github.com/MinkTec/quick_blue
      ref: HEAD
      path: quick_blue_platform_interface
  bluez: ^0.8.1
  collection: ^1.15.0
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: QuickBlueLinux
